---
abstract: 'A library for interacting with version-control systems.'
author:
  - 'Max Kanat-Alexander <mkanat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: VCI
name: VCI
no_index:
  directory:
    - inc
    - t
recommends:
  Git: 0
  SVN::Core: 1.2.0
requires:
  DateTime: 0
  DateTime::Format::DateParse: 0
  IPC::Cmd: 0.42
  LWP::UserAgent: 0
  Module::Load::Conditional: 0.24
  Moose: 0.27
  MooseX::Method: 0
  Path::Abstract: 0.093
  Text::Diff::Parser: 0.07
  XML::Simple: 0
  perl: 5.8.0
resources:
  homepage: http://vci.everythingsolved.com/
  license: http://dev.perl.org/licenses/
  repository: bzr://bzr.everythingsolved.com/vci/stable
version: 0.7.0_1
